export const categoryInfo = {
  artanddesign: 'Curated articles on creativity and design',
  'australia-news': 'Latest headlines and stories from Australia',
  cities: 'Urban insights, culture, and local issues',
  environment: 'Coverage on nature, climate, and conservation',
  fashion: 'Trends, style inspiration, and industry updates',
  film: 'Movie news, reviews, and film culture',
  food: 'Culinary stories, recipes, and foodie trends',
  football: 'Match updates, analysis, and football news',
  games: 'Gaming news, reviews, and industry updates',
  music: 'New releases, artist stories, and music culture',
  news: 'Top global headlines and breaking news',
  politics: 'Political analysis, elections, and government news',
  science: 'Discoveries, research updates, and innovations',
  sport: 'Scores, highlights, and major sports stories',
  technology: 'Tech trends, gadgets, and digital innovation',
  travel: 'Destinations, tips, and travel inspiration',
  'uk-news': 'Updates and headlines from the UK',
  'us-news': 'Updates and headlines from the USA',
  weather: 'Forecasts, climate alerts, and conditions',
  world: 'International stories and global perspectives',
};
